### ISSUE TITLE
Deploy setup for Now v2

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/contrast-swatch#1]
I have literally no idea how to deploy this to Now v2. There are two apps: 1. image microservice built with `micro` and 2. a Gatsby site for the landing page.

- Routes with `/:foreground/:background` should go to the image service
- All other routes should go to the Gatsby site

**Comment by ynnoj** [comment]
@jxnblk I'm not sure your preferred routing structure is possible. 

Using the routing configuration, `/:foreground/:background` would be treat as [route parameters](https://zeit.co/docs/v2/deployments/routes/#route-parameters), which is essence is still the root of the monorepo (and therefore conflicting with the Gatsby build).

I have it working with:

```
"routes": [
    {
      "src": "/img/(?<foreground>[^/]+)/(?<background>[^/]+)",
      "dest": "/img/index.js?foreground=$foreground&background=$background"
    },
    {
      "src": "/(.*)",
      "dest": "/www/$1"
    }
  ]
```

But would be a breaking change 😕

**Comment by jxnblk** [comment]
Ah! I thought there was a way to make 404s fall through to the next route, but maybe I misunderstood... let me think about how to work with this since I'd really like to keep the image URLs the way they are

**Comment by ynnoj** [comment]
@jxnblk Sure! There's a couple commits on my fork anyway. Tidied the function a little too as `micro` isn't really needed when you use the platform [builders](https://zeit.co/docs/v2/deployments/builders/overview).

https://github.com/ynnoj/contrast-swatch
